twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    glo
    format_date: 'd/m/Y H:m'
 

when@test:
    twig:
        strict_variables: true
