twig:
    default_path: '%kernel.project_dir%/templates'
    # config/packages/twig.yaml
twig:
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    # ...

when@test:
    twig:
        strict_variables: true
